### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by anquandebaihuli** [CokeSR/Hk4e-SDKSever-Py#8]
Python用哪一个版本运行呢，还是代码本身有问题
`[Yswj@localhost Hk4e-SDKSever-Py-CokeSR]$ python3.9 main.py 
Traceback (most recent call last):
  File "/opt/Genshin-server/2.8_live/Hk4e-SDKSever-Py-CokeSR/main.py", line 22, in <module>
    import function.dispatch
  File "/opt/Genshin-server/2.8_live/Hk4e-SDKSever-Py-CokeSR/function/dispatch.py", line 66
    '''
    ^
SyntaxError: invalid syntax
`

**Comment by CokeSR** [comment]
不看readme是这样的

**Comment by CokeSR** [comment]
可以给function/dispatch下的query_cur_region方法补全 然后再试

**Comment by anquandebaihuli** [comment]
如何补呢

**Comment by CokeSR** [comment]
用最新推送的吧

**Comment by anquandebaihuli** [comment]
下载的就是最新推送的了，刚才下载的
